apiVersion: apps/v1 # Specifies the API version
kind: Deployment
metadata:
  name: platforms-deployment
spec:
  replicas: 1
  selector: # Selecting template we'll be using
    matchLabels:
      app: platformservice
  template: # Defining pod/container we'll use
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
        - name: platformservice
          image: asandell/platformservice:latest
